#! /bin/sh

sxhkd &
feh --bg-fill ~/Desktop/Pictures/once/neo/HL2.jpg &
 xmodmap ~/.xmodmap
# xrandr --output VGA-0 --rotate left &
# xrandr --output eDP-1 left-of VGA-0 &
# oneko -tora &
./Script/Core/clash -f ~/Script/Core/2.yaml &
 compton -b
./.config/polybar/launch.sh &
./.Conky/startconky.sh &
XDG_SESSION_TYPE=x11 plank &


bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config border_width         2
bspc config window_gap          12

#bspc config split_ratio          0.52
#bspc config borderless_monocle   false
#bspc config gapless_monocle      false

#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
